services:
  nvidia:
    container_name: ros2-vim
    extends:
      service: dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  dev:
    container_name: ros2-vim
    network_mode: host
    build:
      context: ..
      dockerfile: ./ros2-vim/Dockerfile
      ssh:
        - default
    stdin_open: true
    tty: true
    entrypoint: ["/entrypoint.sh", "zsh"]
    working_dir: /home/ros-user/uuv/ros2
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - type: bind
        source: ${HOME}/uuv
        target: /home/ros-user/uuv
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /var/run/avahi-daemon/socket
        target: /var/run/avahi-daemon/socket
      - type: bind
        source: ${HOME}/Documents/ros2-vim/nvim
        target: /home/ros-user/.config/nvim
      - "ros2_zsh_history:/zsh_history"
      - nvim_data:/home/ros-user/.local/share/nvim
      - $SSH_AUTH_SOCK:/ssh-agent
      - "~/.gitconfig:/etc/gitconfig"

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - SHELL=/usr/bin/zsh
      - ROS_WORKSPACE=/home/ros-user/uuv/ros2
      - SSH_AUTH_SOCK=/ssh-agent
      - TERM=xterm-256color
      - COLORTERM=24bit
      - ROS_DOMAIN_ID=29

volumes:
  ros2_zsh_history:
  nvim_data:
